[package]
name = "clang-ast"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "1.7"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
clang-ast-test-suite = { version = "0", path = "tests/clone" }

[workspace]
