[package]
name = "clang-ast"
version = "0.1.7" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
description = "Data structures for processing Clang's `-ast-dump=json` format"
documentation = "https://docs.rs/clang-ast"
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dtolnay/clang-ast"

[dependencies]
serde = "1.0"

[dev-dependencies]
clang-ast-test-suite = { version = "0", path = "tests/clone" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
